/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("dogbreed").del();
  await knex("dogbreed").insert([
    {
      id: 1,
      image_link: "https://api-ninjas.com/images/dogs/golden_retriever.jpg",
      shedding: 4,
      grooming: 2,
      coat_length: 1,
      good_with_strangers: 5,
      playfulness: 4,
      protectiveness: 3,
      trainability: 5,
      energy: 3,
      barking: 1,
      max_height_male: 24.0,
      max_height_female: 24.0,
      max_weight_male: 75.0,
      max_weight_female: 65.0,
      min_height_male: 23.0,
      min_height_female: 23.0,
      min_weight_male: 65.0,
      min_weight_female: 55.0,
      name: "Golden Retriever",
    },
    {
      id: 2,
      image_link: "https://api-ninjas.com/images/dogs/shih_tzu.jpg",
      shedding: 1,
      grooming: 4,
      coat_length: 1,
      good_with_strangers: 3,
      playfulness: 3,
      protectiveness: 3,
      trainability: 4,
      energy: 3,
      barking: 3,
      max_height_male: 10.5,
      max_height_female: 10.5,
      max_weight_male: 16,
      max_weight_female: 16,
      min_height_male: 9,
      min_height_female: 9,
      min_weight_male: 9,
      min_weight_female: 9,
      name: "Shih Tzu",
    },

    {
      id: 3,
      image_link: "https://api-ninjas.com/images/dogs/bulldog.jpg",
      shedding: 3,
      grooming: 3,
      coat_length: 1,
      good_with_strangers: 4,
      playfulness: 4,
      protectiveness: 3,
      trainability: 4,
      energy: 3,
      barking: 2,
      max_height_male: 15,
      max_height_female: 15,
      max_weight_male: 50,
      max_weight_female: 40,
      min_height_male: 14,
      min_height_female: 14,
      min_weight_male: 50,
      min_weight_female: 40,
      name: "Bulldog",
    },
    {
      id: 4,
      image_link: "https://api-ninjas.com/images/dogs/poodle_(miniature).jpg",
      shedding: 1,
      grooming: 4,
      coat_length: 1,
      good_with_strangers: 5,
      playfulness: 5,
      protectiveness: 3,
      trainability: 5,
      energy: 4,
      barking: 4,
      max_height_male: 15,
      max_height_female: 15,
      max_weight_male: 15,
      max_weight_female: 15,
      min_height_male: 10,
      min_height_female: 10,
      min_weight_male: 10,
      min_weight_female: 10,
      name: "Poodle (Miniature)",
    },
    {
      id: 5,
      image_link: "https://api-ninjas.com/images/dogs/dachshund.jpg",
      shedding: 2,
      grooming: 2,
      coat_length: 2,
      good_with_strangers: 4,
      playfulness: 4,
      protectiveness: 4,
      trainability: 4,
      energy: 3,
      barking: 5,
      max_height_male: 9,
      max_height_female: 9,
      max_weight_male: 32,
      max_weight_female: 32,
      min_height_male: 8,
      min_height_female: 8,
      min_weight_male: 16,
      min_weight_female: 16,
      name: "Dachshund",
    },
    {
      id: 6,
      image_link: "https://api-ninjas.com/images/dogs/boston_terrier.jpg",
      shedding: 2,
      grooming: 2,
      coat_length: 1,
      good_with_strangers: 5,
      playfulness: 5,
      protectiveness: 3,
      trainability: 4,
      energy: 4,
      barking: 2,
      max_height_male: 17,
      max_height_female: 17,
      max_weight_male: 25,
      max_weight_female: 25,
      min_height_male: 15,
      min_height_female: 15,
      min_weight_male: 12,
      min_weight_female: 12,
      name: "Boston Terrier",
    },
    {
      id: 7,
      image_link: "https://api-ninjas.com/images/dogs/shetland_sheepdog.jpg",
      shedding: 3,
      grooming: 3,
      coat_length: 1,
      good_with_strangers: 2,
      playfulness: 5,
      protectiveness: 5,
      trainability: 5,
      energy: 4,
      barking: 5,
      max_height_male: 16,
      max_height_female: 16,
      max_weight_male: 25,
      max_weight_female: 25,
      min_height_male: 13,
      min_height_female: 13,
      min_weight_male: 15,
      min_weight_female: 15,
      name: "Shetland Sheepdog",
    },
    {
      id: 8,
      image_link: "https://api-ninjas.com/images/dogs/siberian_husky.jpg",
      shedding: 4,
      grooming: 2,
      coat_length: 1,
      good_with_strangers: 5,
      playfulness: 5,
      protectiveness: 1,
      trainability: 3,
      energy: 5,
      barking: 5,
      max_height_male: 23.5,
      max_height_female: 23.5,
      max_weight_male: 60,
      max_weight_female: 50,
      min_height_male: 21,
      min_height_female: 21,
      min_weight_male: 45,
      min_weight_female: 35,
      name: "Siberian Husky",
    },
    {
      id: 9,
      image_link: "https://api-ninjas.com/images/dogs/rottweiler.jpg",
      shedding: 3,
      grooming: 1,
      coat_length: 1,
      good_with_strangers: 3,
      playfulness: 4,
      protectiveness: 5,
      trainability: 5,
      energy: 3,
      barking: 1,
      max_height_male: 27,
      max_height_female: 27,
      max_weight_male: 135,
      max_weight_female: 100,
      min_height_male: 24,
      min_height_female: 24,
      min_weight_male: 95,
      min_weight_female: 80,
      name: "Rottweiler",
    },
    {
      id: 10,
      image_link: "https://api-ninjas.com/images/dogs/german_shepherd_dog.jpg",
      shedding: 4,
      grooming: 2,
      coat_length: 1,
      good_with_strangers: 3,
      playfulness: 4,
      protectiveness: 5,
      trainability: 5,
      energy: 5,
      barking: 3,
      max_height_male: 26,
      max_height_female: 26,
      max_weight_male: 90,
      max_weight_female: 70,
      min_height_male: 24,
      min_height_female: 24,
      min_weight_male: 65,
      min_weight_female: 50,
      name: "German Shepherd Dog",
    },
    {
      image_link: "https://api-ninjas.com/images/dogs/great_dane.jpg",
      shedding: 3,
      grooming: 1,
      coat_length: 1,
      good_with_strangers: 3,
      playfulness: 4,
      protectiveness: 5,
      trainability: 3,
      energy: 4,
      barking: 3,
      max_height_male: 32,
      max_height_female: 32,
      max_weight_male: 175,
      max_weight_female: 140,
      min_height_male: 30,
      min_height_female: 30,
      min_weight_male: 140,
      min_weight_female: 110,
      name: "Great Dane",
    },
    {
      id: 11,
      image_link: "https://api-ninjas.com/images/dogs/boxer.jpg",
      shedding: 2,
      grooming: 2,
      coat_length: 1,
      good_with_strangers: 4,
      playfulness: 4,
      protectiveness: 4,
      trainability: 4,
      energy: 4,
      barking: 3,
      max_height_male: 25,
      max_height_female: 25,
      max_weight_male: 80,
      max_weight_female: 65,
      min_height_male: 23,
      min_height_female: 23,
      min_weight_male: 65,
      min_weight_female: 50,
      name: "Boxer",
    },
    {
      id: 12,
      image_link: "https://api-ninjas.com/images/dogs/shiba_inu.jpg",
      shedding: 3,
      grooming: 2,
      coat_length: 1,
      good_with_strangers: 3,
      playfulness: 3,
      protectiveness: 5,
      trainability: 2,
      energy: 3,
      barking: 3,
      max_height_male: 16.5,
      max_height_female: 16.5,
      max_weight_male: 23,
      max_weight_female: 17,
      min_height_male: 14.5,
      min_height_female: 14.5,
      min_weight_male: 23,
      min_weight_female: 17,
      name: "Shiba Inu",
    },
    {
      id: 13,
      image_link: "https://api-ninjas.com/images/dogs/havanese.jpg",
      shedding: 2,
      grooming: 3,
      coat_length: 1,
      good_with_strangers: 5,
      playfulness: 5,
      protectiveness: 3,
      trainability: 4,
      energy: 3,
      barking: 4,
      max_height_male: 11.5,
      max_height_female: 11.5,
      max_weight_male: 13,
      max_weight_female: 13,
      min_height_male: 8.5,
      min_height_female: 8.5,
      min_weight_male: 7,
      min_weight_female: 7,
      name: "Havanese",
    },
    {
      id: 14,
      image_link: "https://api-ninjas.com/images/dogs/cocker_spaniel.jpg",
      shedding: 3,
      grooming: 4,
      coat_length: 1,
      good_with_strangers: 4,
      playfulness: 3,
      protectiveness: 3,
      trainability: 4,
      energy: 4,
      barking: 3,
      max_height_male: 15.5,
      max_height_female: 15.5,
      max_weight_male: 30,
      max_weight_female: 25,
      min_height_male: 14.5,
      min_height_female: 14.5,
      min_weight_male: 25,
      min_weight_female: 20,
      name: "Cocker Spaniel",
    },
    {
      id: 15,
      image_link: "https://api-ninjas.com/images/dogs/doberman_pinscher.jpg",
      shedding: 4,
      grooming: 1,
      coat_length: 1,
      good_with_strangers: 4,
      playfulness: 4,
      protectiveness: 5,
      trainability: 5,
      energy: 5,
      barking: 3,
      max_height_male: 28,
      max_height_female: 28,
      max_weight_male: 100,
      max_weight_female: 90,
      min_height_male: 26,
      min_height_female: 26,
      min_weight_male: 75,
      min_weight_female: 60,
      name: "Doberman Pinscher",
    },
    {
      id: 16,
      image_link: "https://api-ninjas.com/images/dogs/bullmastiff.jpg",
      shedding: 3,
      grooming: 1,
      coat_length: 1,
      good_with_strangers: 3,
      playfulness: 3,
      protectiveness: 5,
      trainability: 4,
      energy: 4,
      barking: 1,
      max_height_male: 27,
      max_height_female: 27,
      max_weight_male: 130,
      max_weight_female: 120,
      min_height_male: 25,
      min_height_female: 25,
      min_weight_male: 110,
      min_weight_female: 100,
      name: "Bullmastiff",
    },
    {
      id: 17,
      image_link: "https://api-ninjas.com/images/dogs/maltese.jpg",
      shedding: 1,
      grooming: 4,
      coat_length: 1,
      good_with_strangers: 3,
      playfulness: 3,
      protectiveness: 4,
      trainability: 3,
      energy: 3,
      barking: 3,
      max_height_male: 9,
      max_height_female: 9,
      max_weight_male: 8.8,
      max_weight_female: 8.8,
      min_height_male: 7,
      min_height_female: 7,
      min_weight_male: 6.6,
      min_weight_female: 6.6,
      name: "Maltese",
    },
    {
      id: 18,
      image_link: "https://api-ninjas.com/images/dogs/border_collie.jpg",
      shedding: 3,
      grooming: 3,
      coat_length: 1,
      good_with_strangers: 4,
      playfulness: 5,
      protectiveness: 3,
      trainability: 5,
      energy: 5,
      barking: 4,
      max_height_male: 22,
      max_height_female: 22,
      max_weight_male: 55,
      max_weight_female: 55,
      min_height_male: 19,
      min_height_female: 19,
      min_weight_male: 30,
      min_weight_female: 30,
      name: "Border Collie",
    },
    {
      id: 19,
      image_link: "https://api-ninjas.com/images/dogs/vizsla.jpg",
      shedding: 3,
      grooming: 2,
      coat_length: 1,
      good_with_strangers: 4,
      playfulness: 5,
      protectiveness: 3,
      trainability: 5,
      energy: 5,
      barking: 3,
      max_height_male: 24,
      max_height_female: 24,
      max_weight_male: 60,
      max_weight_female: 55,
      min_height_male: 22,
      min_height_female: 22,
      min_weight_male: 55,
      min_weight_female: 44,
      name: "Vizsla",
    },
    {
      id: 20,
      image_link: "https://api-ninjas.com/images/dogs/beagle.jpg",
      good_with_children: 5,
      good_with_other_dogs: 5,
      shedding: 3,
      grooming: 2,
      drooling: 1,
      coat_length: 1,
      good_with_strangers: 3,
      playfulness: 4,
      protectiveness: 2,
      trainability: 3,
      energy: 4,
      barking: 4,
      min_life_expectancy: 10,
      max_life_expectancy: 15,
      max_height_male: 16,
      max_height_female: 15,
      max_weight_male: 20,
      max_weight_female: 30,
      min_height_male: 14,
      min_height_female: 13,
      min_weight_male: 15,
      min_weight_female: 20,
      name: "Beagle",
    },
  ]);
};
